version: '3.5'
services:
  test-db:
    image: mysql:8
    tmpfs: /var/lib/mysql
    container_name: test-db.microservice.internal
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: microservice-test
networks:
  default:
    name: microservice-test
